{% set name = "sb3-contrib" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sb3_contrib-{{ version }}.tar.gz
  sha256: 9755ef9efa08e43afb9c4e79564ed594eb8bc497256920403a7e269a72216221

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - stable-baselines3 >=2.0.0

test:
  imports:
    - sb3_contrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib
  summary: Contrib package of Stable Baselines3, experimental code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YYYasin19
