{% set name = "sb3-contrib" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sb3_contrib-{{ version }}.tar.gz
  sha256: 87281ae64e6965e46ac24b58778241d2b07b29996044491267ed844c1a75acfe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - stable-baselines3 >=2.0.0

test:
  imports:
    - sb3_contrib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib
  summary: Contrib package of Stable Baselines3, experimental code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YYYasin19
